// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmIWIRMBEZ-UU7E2xkVb8uF2pBMaKtwxU',
    appId: '1:901667678702:web:46e07a706146b284fa46ff',
    messagingSenderId: '901667678702',
    projectId: 'rekeep-c8016',
    authDomain: 'rekeep-c8016.firebaseapp.com',
    storageBucket: 'rekeep-c8016.firebasestorage.app',
    measurementId: 'G-F7GYDFJ8P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiGoA-8DLAD5KHqZOmdw6I6zUIe0vGHWc',
    appId: '1:901667678702:android:04cdf848728699bdfa46ff',
    messagingSenderId: '901667678702',
    projectId: 'rekeep-c8016',
    storageBucket: 'rekeep-c8016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtk3fjOGTVDo9sb-7egkAMdeWuUkeO10',
    appId: '1:901667678702:ios:4eb4d8a927bca0e4fa46ff',
    messagingSenderId: '901667678702',
    projectId: 'rekeep-c8016',
    storageBucket: 'rekeep-c8016.firebasestorage.app',
    iosBundleId: 'com.example.flutterRekeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtk3fjOGTVDo9sb-7egkAMdeWuUkeO10',
    appId: '1:901667678702:ios:4eb4d8a927bca0e4fa46ff',
    messagingSenderId: '901667678702',
    projectId: 'rekeep-c8016',
    storageBucket: 'rekeep-c8016.firebasestorage.app',
    iosBundleId: 'com.example.flutterRekeep',
  );
}
